language: ruby
rvm:
- 2.1

install:
  - ./script/bootstrap
script:
  - ./script/build-production && htmlproof ./_site --disable-external --empty-alt-ignore

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master
