title: TyLauncher
email: luckytianyiyan@gmail.com
baseurl: 'http://www.tylauncher.com'
twitter_username: luckytianyiyan
github_username: luckytianyiyan
blog: 'http://blog.tianyiyan.com'
github:
    repository_url: 'https://github.com/luckytianyiyan/TyLauncher'
    releases_url: 'https://github.com/luckytianyiyan/TyLauncher/releases'
    owner_url: 'https://github.com/luckytianyiyan'
    owner_name: luckytianyiyan
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: rouge
last_version: 2.2.0.0

permalink: /:title/
languages: ["en", "cn"]
