# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TyLauncher
email: luckytianyiyan@gmail.com
description: 'A file quick launch tool.'
baseurl: 'http://www.tylauncher.com'
twitter_username: luckytianyiyan
github_username:  luckytianyiyan
blog: "http://blog.tianyiyan.com"

github:
  repository_url: "https://github.com/luckytianyiyan/TyLauncher"
  releases_url: "https://github.com/luckytianyiyan/TyLauncher/releases"
  owner_url: "https://github.com/luckytianyiyan"
  owner_name: "luckytianyiyan"

# Build settings
# markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments
